---
apiVersion: v2
appVersion: 1.19.1
description: Bridges events and allows you to control your Zigbee devices via MQTT
name: zigbee2mqtt
version: 1.19.1
kubeVersion: ">=1.16.0-0"
keywords:
  - zigbee
  - mqtt
  - home-assistant
home: https://github.com/roeidalm/helm-chart/tree/main/charts/zigbee2mqtt
icon: https://raw.githubusercontent.com/Koenkk/zigbee2mqtt/master/images/logo.png
sources:
  - https://github.com/Koenkk/zigbee2mqtt
maintainers:
  - name: roei dalmedigos
    email: dalmedigos@gmail.com
dependencies:
  - name: common
    repository: https://library-charts.k8s-at-home.com
    version: 4.5.2
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Upgraded `common` chart dependency to version 4.5.2