apiVersion: v2
name: home-assistant-matter-hub
version: 3.0.2
appVersion: 3.0.2
description: Helm chart for deploying Home Assistant Matter Hub
type: application
home: https://github.com/roeidalm/helm-chart/tree/main/charts/home-assistant-matter-hub
icon: https://raw.githubusercontent.com/Luligu/matterbridge/main/frontend/public/matterbridge%20624x624.png
kubeVersion: ">=1.16.0-0"
maintainers:
  - name: roeidalm
    email: dalmedigos@gmail.com
dependencies:
  - name: common
    repository: https://library-charts.k8s-at-home.com
    version: 4.5.2
keywords:
  - home-assistant
  - matter
  - iot
  - smart-home
annotations:
  selfUsages.search-tag: "\\b\\d+\\.\\d+\\.\\d+\\b$"
  selfUsages.image_name: luligu/matterbridge
