apiVersion: v2
name: home-assistant-matter-hub
version: 2.2.5
appVersion: 2.2.5
description: Helm chart for deploying Home Assistant Matter Hub
type: application
home: https://github.com/roeidalm/helm-chart/tree/main/charts/home-assistant-matter-hub
icon: https://github.com/Luligu/matterbridge/blob/main/frontend/public/matterbridge.svg
kubeVersion: ">=1.16.0-0"
maintainers:
  - name: roeidalm
    email: dalmedigos@gmail.com
dependencies:
  - name: common
    repository: https://library-charts.k8s-at-home.com
    version: 4.5.2
keywords:
  - home-assistant
  - matter
  - iot
  - smart-home
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Upgraded `common` chart dependency to version 4.5.2
  artifacthub.io/search-tag: none
  artifacthub.io/images: luligu/matterbridge